### ISSUE TITLE
KOPTReader crashing with multi-thread precache enabled.

### ISSUE THREAD

**Issue by tigran123** [koreader/kindlepdfviewer#592]
Open the ideal file for testing KPV reflow (as it shows bugs, e.g. #546)

https://github.com/downloads/tigran123/libdjvu/Ideal-pdf-reflow-test.pdf

Enable multi-threading and then start paging quickly. After 5-10 seconds or so it coredumps with segmentation violation.

**Comment by tigran123** [comment]
Here is the stack trace:

```
New LWP 2854]
[New LWP 2864]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./kpdfview.emulator ./reader.lua ../Books'.
Program terminated with signal 11, Segmentation fault.
#0  word_gaps_add (median_gap=<synthetic pointer>, lcheight=20, breakinfo=<optimized out>) at k2pdfopt.c:4922
4922                (*median_gap) = gap_sorted[n / 2];
Missing separate debuginfos, use: debuginfo-install SDL-1.2.14-16.fc17.x86_64 glibc-2.15-57.fc17.x86_64 libX11-1.5.0-2.fc17.x86_64 libXau-1.0.6-3.fc17.x86_64 libXcursor-1.1.13-1.fc17.x86_64 libXfixes-5.0-2.fc17.x86_64 libXrender-0.9.7-1.fc17.x86_64 libjpeg-turbo-1.2.1-1.fc17.x86_64 libxcb-1.8.1-1.fc17.x86_64
(gdb) bt
#0  word_gaps_add (median_gap=<synthetic pointer>, lcheight=20, breakinfo=<optimized out>) at k2pdfopt.c:4922
#1  bmpregion_one_row_find_breaks (region=region@entry=0x7fffdf41ab20, breakinfo=breakinfo@entry=0x7fffdf41aaa0, colcount=colcount@entry=0x1353480, 
    rowcount=rowcount@entry=0x1516ab0, add_to_dbase=1) at k2pdfopt.c:4145
#2  0x00007fe9b1c2967e in bmpregion_one_row_wrap_and_add (pi=0, rowbase=494, mean_row_gap=27, line_spacing=56, pageinfo=0x0, rowcount=0x1516ab0, colcount=0x1353480, 
    justflags=3, masterinfo=0x7fe9b1e34fc0, i2=24, i1=7, index=9, rowbreakinfo=0x7fffdf41e180, region=0x7fffdf41aac0, marking_flags=<optimized out>) at k2pdfopt.c:4201
#3  bmpregion_analyze_justification_and_line_spacing (region=0x4024578578578579, region@entry=0x7fffdf41ae80, breakinfo=breakinfo@entry=0x7fffdf41e180, 
    masterinfo=masterinfo@entry=0x7fe9b1e34fc0, colcount=colcount@entry=0x1353480, rowcount=0x1516ab0, pageinfo=pageinfo@entry=0x0, allow_text_wrapping=1, 
    force_scale=force_scale@entry=-1) at k2pdfopt.c:3185
#4  0x00007fe9b1c2a59b in bmpregion_add (region=region@entry=0x7fffdf41e1b0, breakinfo=breakinfo@entry=0x7fffdf41e180, masterinfo=masterinfo@entry=0x7fe9b1e34fc0, 
    allow_text_wrapping=allow_text_wrapping@entry=1, trim_flags=trim_flags@entry=15, allow_vertical_breaks=allow_vertical_breaks@entry=1, force_scale=force_scale@entry=-1, 
    justification_flags=justification_flags@entry=143, caller_id=caller_id@entry=1, colcount=colcount@entry=0x1353480, rowcount=rowcount@entry=0x1516ab0, 
    pageinfo=pageinfo@entry=0x0, rowbase_delta=-1, rowbase_delta@entry=33, mark_flags=<optimized out>) at k2pdfopt.c:1732
#5  0x00007fe9b1c2d458 in bmpregion_vertically_break (region=region@entry=0x7fffdf41e400, masterinfo=masterinfo@entry=0x7fe9b1e34fc0, allow_text_wrapping=1, 
    force_scale=-1, colcount=colcount@entry=0x1353480, rowcount=rowcount@entry=0x1516ab0, pageinfo=pageinfo@entry=0x0, colgap_pixels=1, ncols=ncols@entry=1)
    at k2pdfopt.c:1559
#6  0x00007fe9b1c2ff4b in bmpregion_source_page_add (region=<optimized out>, masterinfo=0x7fe9b1e34fc0, level=1, pageinfo=0x0, colgap0_pixels=75) at k2pdfopt.c:862
#7  0x00007fe9b1c329f3 in k2pdfopt_reflow_bmp (kctx=kctx@entry=0x415452d0) at k2pdfopt.c:483
#8  0x0000000000409270 in reflowPage (L=<optimized out>) at pdf.c:620
#9  0x00007fe9b160f78b in ?? () from libs-emu/libluajit-5.1.so.2
#10 0x00007fe9b161c5c0 in lua_pcall () from libs-emu/libluajit-5.1.so.2
#11 0x0000000000407fd6 in main (argc=<optimized out>, argv=0x7fffdf420288) at kpdfview.c:78
(gdb) 
```

**Comment by chrox** [comment]
Yes. I can repeat this bug in the emulator by keep pressing on Page_Down without a key release. Then core will be dumped in several seconds. I will look into this more carefully. Thanks.

**Comment by tigran123** [comment]
The fix is in master, so closing the issue.
